export const phaseColors: Record<string, string> = {
    Research: '#3B82F6', Build: '#8B5CF6', Deploy: '#10B981', Optimize: '#F59E0B',
    Authority: '#EC4899', Convert: '#EF4444', Track: '#06B6D4', Reports: '#84CC16', Automation: '#F97316'
}

export interface Tool { name: string; desc: string; free: boolean; users: string }

export const toolsByPhase: Record<string, Tool[]> = {
    Research: [
        { name: 'AI Niche Finder (Custom Criteria)', desc: 'Core tool for finding low-competition niches', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Guided Niche Wizard', desc: 'Step-by-step niche selection for beginners', free: true, users: '🆕' },
        { name: 'SERP Feature Analyzer', desc: 'Analyze what features dominate SERPs', free: false, users: '🆕💼🏠🏢🤖' },
        { name: 'Local SERP Landscape Report', desc: 'Full SERP landscape analysis', free: false, users: '💼🏠🏢🤖' },
        { name: 'Competitor Menu/Nav Finder', desc: 'Find competitor site structure', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Competitor Section Structure Analyzer', desc: 'Analyze competitor page sections', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Competitor Entity Extractor', desc: 'Extract entities from competitor sites', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Local Business Directory Scanner', desc: 'Scan local business directories', free: false, users: '💼🏠🏢🤖' },
        { name: 'Competitor GBP Spy', desc: 'Spy on competitor Google Business Profiles', free: false, users: '💼🏠🏢🤖' },
        { name: 'Competitor Rank Comparator', desc: 'Side-by-side ranking comparison', free: false, users: '💼🏢🤖' },
        { name: 'Competitor Content Gap Report', desc: 'Find content gaps vs competitors', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'AI Local Keyword Generator', desc: 'Generate local intent keywords', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Service + City Keyword Combiner', desc: 'Bulk keyword matrix generator', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Keyword Difficulty Estimator', desc: 'AI-based competition analysis', free: false, users: '💼🏠🏢🤖' },
        { name: 'Topical Authority Mapper', desc: 'Map topic clusters for authority', free: true, users: '💼🏢🤖' },
        { name: 'Local Intent Keyword Scorer', desc: 'Score keywords by local intent', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Internal Keyword Mapping Tool', desc: 'Map keywords to correct pages', free: true, users: '💼🏠🏢🤖' },
    ],
    Build: [
        { name: 'AI Elementor Auto Page Generator', desc: 'Core AI engine: generates full Elementor JSON', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'AI Website Generator (WP+Elementor)', desc: 'Complete WordPress site generator', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Static Website Generator (HTML/CSS)', desc: 'LocalSitesPro-style static sites', free: true, users: '🏠🤖' },
        { name: 'Local SEO Structure Enforcer', desc: 'Enforces correct SEO structure', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Homepage SEO Layout Builder', desc: 'SEO-optimized homepage layouts', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Service Page Generator', desc: 'Auto-creates service pages', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Location Page Generator', desc: 'City/area location pages with NAP', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Near-Me Page Generator', desc: 'Near-me intent targeted pages', free: true, users: '🏠🏢🤖' },
        { name: 'Elementor Section Auto-Builder', desc: 'AI generates Elementor sections', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Rank & Rent Website Blueprint', desc: 'Pre-built R&R site layouts', free: true, users: '🏠🤖' },
        { name: 'AI Local Content Writer (Gemini)', desc: 'Writes all content using Gemini', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Entity-Based Content Section Builder', desc: 'Builds content from extracted entities', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'City-Specific Content Generator', desc: 'City-level content variations', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Service + City Content Combiner', desc: 'Unique pages per service+city', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'FAQ Schema Content Generator', desc: 'Conversational FAQ content', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'E-E-A-T Content Booster', desc: 'Adds expertise & trust signals', free: true, users: '💼🏢🤖' },
        { name: 'AI Content Rewriter (Localization)', desc: 'Rewrites for different cities', free: true, users: '🏠🏢🤖' },
        { name: 'Topical Content Cluster Builder', desc: 'Topic cluster architecture', free: true, users: '💼🏢🤖' },
        { name: 'Local Landing Page A/B Variant Gen', desc: 'Multiple page variants', free: true, users: '🏠🏢🤖' },
        { name: 'Zero-Click Search Optimizer', desc: 'Featured snippet optimization', free: true, users: '💼🏢🤖' },
        { name: 'Video SEO Script Generator', desc: 'Scripts for Reels/Shorts', free: true, users: '💼🏢🤖' },
        { name: 'AI Design Generator (Tokens)', desc: 'Colors, fonts, spacing tokens', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Local SEO Theme Selector', desc: 'Local Basic/Premium/R&R presets', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'CTA Placement Optimizer', desc: 'AI places CTAs optimally', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Conversion-Focused Layout Engine', desc: 'CRO-optimized layouts', free: true, users: '💼🏢🤖' },
        { name: 'Image Geo-Tagging Tool', desc: 'Adds GPS EXIF to images', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Image Compression & SEO Tool', desc: 'Compress + auto ALT text', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'GMB Image Optimizer & Metadata', desc: 'Geo-tag for GBP images', free: false, users: '💼🏢🤖' },
        { name: 'Image ALT Text Generator', desc: 'Local keyword-rich ALT text', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Google Map Embed Generator', desc: 'Map embed for every page', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'NAP Block Generator', desc: 'Schema-ready NAP blocks', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Directions/Embed URL Generator', desc: 'Google Maps directions links', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Local Trust Signal Block Generator', desc: 'Years/certs/awards blocks', free: true, users: '🆕💼🏠🏢🤖' },
    ],
    Deploy: [
        { name: 'Custom Domain Deploy Manager', desc: 'Deploy to custom domains', free: true, users: '🏠🏢🤖' },
        { name: 'Subdomain Deploy Option', desc: 'Deploy to subdomains for testing', free: true, users: '🏠🤖' },
        { name: 'Netlify/Vercel Auto Hosting', desc: 'One-click cloud hosting', free: true, users: '🏠🏢🤖' },
        { name: 'Ultra-Fast Hosting Presets', desc: 'Pre-configured CDN settings', free: true, users: '🏠🏢🤖' },
        { name: 'WordPress Export Package Builder', desc: 'WP-ready ZIP package', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Elementor JSON Template Exporter', desc: 'Direct Elementor import', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Static to WordPress Migration Tool', desc: 'Hybrid static to WP mode', free: true, users: '🏠🏢🤖' },
        { name: 'Bulk Page Publisher WP Plugin', desc: '5000 pages in 10 minutes', free: true, users: '🏠🤖' },
    ],
    Optimize: [
        { name: 'Title & Meta Generator', desc: 'SEO-optimized titles and metas', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Header Structure Optimizer', desc: 'H1-H6 hierarchy enforcer', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Schema Markup Generator', desc: 'JSON-LD schema auto-inject', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Local Business JSON-LD Full Generator', desc: 'Complete structured data', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Review Schema Generator', desc: 'Review structured data', free: true, users: '💼🏢🤖' },
        { name: 'Local Event Schema Generator', desc: 'Local events schema', free: true, users: '💼🏢🤖' },
        { name: 'Core Web Vitals Checker', desc: 'Speed & performance analysis', free: true, users: '💼🏠🏢🤖' },
        { name: 'Mobile Checker', desc: 'Mobile-friendly audit', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Indexation & Crawl Audit', desc: 'Crawl issues & index bloat', free: true, users: '💼🏠🏢🤖' },
        { name: 'XML Sitemap Generator', desc: 'SEO-friendly sitemaps', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Robots.txt Generator', desc: 'Local SEO robots rules', free: true, users: '💼🏠🏢🤖' },
        { name: 'Technical SEO Audit Tool', desc: 'Full technical audit', free: true, users: '💼🏢🤖' },
        { name: 'Local SEO Full Website Audit', desc: 'Complete local SEO audit', free: true, users: '💼🏢🤖' },
        { name: 'Mobile PRO Fixer (Auto-Fix)', desc: 'Auto-fix mobile issues', free: false, users: '🏢🤖' },
        { name: 'Mass Internal Linking Engine', desc: 'Auto-link at scale', free: true, users: '🏠🤖' },
        { name: 'Silo & Hierarchy Builder', desc: 'Parent/child page structure', free: true, users: '💼🏠🏢🤖' },
        { name: 'SEO Slug Automation Tool', desc: '/service/city/ URL structures', free: true, users: '🏠🤖' },
        { name: 'Programmatic SEO Safety Controller', desc: 'Prevent cannibalization', free: true, users: '🏠🤖' },
    ],
    Authority: [
        { name: 'GBP First-Time Setup Wizard', desc: 'Step-by-step GBP creation', free: false, users: '🆕' },
        { name: 'GBP Audit Tool', desc: 'Full GBP audit + suggestions', free: false, users: '💼🏠🏢🤖' },
        { name: 'GMB Full Audit Tool', desc: 'Complete GMB audit report', free: false, users: '💼🏢🤖' },
        { name: 'GBP Insights Analyzer', desc: 'Views/calls/clicks trends', free: false, users: '💼🏢🤖' },
        { name: 'GBP Spam Fighter/Detector', desc: 'Detects spam & suspension risks', free: false, users: '💼🏠🏢🤖' },
        { name: 'GBP Q&A Auto-Responder', desc: 'AI Q&A with approval workflow', free: false, users: '💼🏢🤖' },
        { name: 'GBP Post Generator', desc: 'AI post templates + scheduling', free: false, users: '💼🏠🏢🤖' },
        { name: 'GBP AI Agent (Auto Management)', desc: 'Unified AI bot for GBP', free: false, users: '🏢🤖' },
        { name: 'GMB Category Finder', desc: 'Correct GMB category suggestions', free: false, users: '🆕💼🏠🏢🤖' },
        { name: 'Duplicate GBP Detector', desc: 'Find & merge duplicate listings', free: false, users: '💼🏢🤖' },
        { name: 'GBP Website Builder', desc: 'AI-generated GBP website', free: false, users: '🆕💼🏢🤖' },
        { name: 'Service Area Boundary Definer', desc: 'Exact service area for GBP', free: false, users: '💼🏠🏢🤖' },
        { name: 'GMB Messaging Auto-Responder', desc: 'AI chat + appointment booking', free: false, users: '💼🏢🤖' },
        { name: 'GMB Post-to-Social Automation', desc: 'GBP posts to Facebook/Instagram', free: false, users: '🏢🤖' },
        { name: 'Multi-Platform Review Aggregator', desc: 'Google+Yelp+Facebook reviews', free: false, users: '💼🏢🤖' },
        { name: 'Review Request Campaign Builder', desc: 'SMS/email review campaigns', free: false, users: '💼🏢🤖' },
        { name: 'Review Response Generator', desc: 'AI-powered review replies', free: false, users: '💼🏠🏢🤖' },
        { name: 'Review Sentiment & Competitor Gap', desc: 'Competitor review analysis', free: false, users: '💼🏢🤖' },
        { name: 'Reputation Score Calculator', desc: 'Overall reputation score', free: false, users: '💼🏢🤖' },
        { name: 'Reputation Builder / Manager', desc: 'Full reputation management', free: false, users: '🏢🤖' },
        { name: 'Automated Review Outreach', desc: 'Auto review request campaigns', free: false, users: '🏢🤖' },
        { name: 'NAP Consistency Checker', desc: 'NAP uniformity across web', free: false, users: '🆕💼🏠🏢🤖' },
        { name: 'Citation Finder', desc: 'Local citation opportunities', free: false, users: '💼🏠🏢🤖' },
        { name: 'Citation Tracker', desc: 'Track published citations', free: false, users: '💼🏢🤖' },
        { name: 'Auto Citation Builder/Submitter', desc: 'Submit to 100+ directories', free: false, users: '🏢🤖' },
        { name: 'Local Citation Manual Manager', desc: 'Manual citation tracking', free: true, users: '💼🏠🏢🤖' },
        { name: 'Duplicate Listings Resolver', desc: 'Auto-detect & merge duplicates', free: false, users: '💼🏢🤖' },
        { name: 'Knowledge Graph Optimizer', desc: 'Push data to Knowledge Graph', free: false, users: '🏢🤖' },
        { name: 'Business Info Sync Tool', desc: 'Auto-sync NAP everywhere', free: false, users: '🏢🤖' },
        { name: 'Hyper-Local Backlink Finder', desc: 'Local backlink opportunities', free: false, users: '💼🏠🏢🤖' },
        { name: 'Link Building Auto (AI-assisted)', desc: 'AI prospect & outreach', free: false, users: '🏢🤖' },
        { name: 'Link Building Manual Tracker', desc: 'Manual outreach CRM', free: true, users: '💼🏠🏢🤖' },
        { name: 'Fast Indexing & URL Pusher', desc: 'Force fast URL indexing', free: false, users: '🏠🏢🤖' },
    ],
    Convert: [
        { name: 'Click-to-Call Button Generator', desc: '#1 local conversion tool', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'WhatsApp Business Link Generator', desc: 'WhatsApp CTA generator', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'Booking/Appointment CTA Generator', desc: 'Booking widget generator', free: true, users: '💼🏢🤖' },
        { name: 'Local Offer/Deal Generator', desc: 'Local deals & offers', free: true, users: '💼🏢🤖' },
        { name: 'Local PPC Campaign Generator', desc: 'Hyper-local Google Ads', free: false, users: '🏢🤖' },
    ],
    Track: [
        { name: 'Geo-Grid Rank Tracker', desc: 'Local keyword positions by ZIP', free: false, users: '💼🏠🏢🤖' },
        { name: 'Local SERP Tracker', desc: 'Track local SERPs + AI overviews', free: false, users: '💼🏠🏢🤖' },
        { name: 'AI Share of Voice Tracker', desc: 'Monitors AI mentions (ChatGPT/Gemini)', free: false, users: '🏢🤖' },
        { name: 'Visibility Score Calculator', desc: 'Overall local visibility score', free: false, users: '💼🏢🤖' },
        { name: 'Service Area Coverage Mapper', desc: 'Visual service area map', free: false, users: '💼🏢🤖' },
        { name: 'Performance Alert System', desc: 'Auto ranking drop alerts', free: false, users: '💼🏢🤖' },
        { name: 'Analytics Integrator (GA+GSC)', desc: 'Google Analytics + Search Console', free: false, users: '💼🏢🤖' },
        { name: 'Local Business Heatmap Analysis', desc: 'Lead density map', free: false, users: '🏢🤖' },
        { name: 'Rank Drop AI Explainer', desc: 'AI explains why rankings dropped', free: true, users: '💼🏢🤖' },
    ],
    Reports: [
        { name: 'Local SEO Checklist Generator', desc: 'Automated SEO checklists', free: true, users: '🆕💼🏠🏢🤖' },
        { name: 'PDF / Dashboard Report Generator', desc: 'Downloadable SEO reports', free: true, users: '💼🏢🤖' },
        { name: 'Client Snapshot View', desc: 'All client KPIs at a glance', free: true, users: '💼🏢🤖' },
        { name: 'Multi-Location Dashboard', desc: 'Agency multi-location view', free: false, users: '🏢🤖' },
        { name: 'White-Label Reporting Customizer', desc: 'Fully branded reports', free: false, users: '🏢🤖' },
        { name: 'Monthly SEO Progress Report', desc: 'Automated monthly reports', free: true, users: '💼🏢🤖' },
        { name: 'Competitor Comparison Report', desc: 'Client vs competitors', free: true, users: '💼🏢🤖' },
        { name: 'Client Onboarding Form Generator', desc: 'Professional client intake', free: true, users: '💼🏢' },
        { name: 'Local SEO Proposal Generator', desc: 'Win clients with AI proposals', free: true, users: '💼🏢' },
        { name: 'CRM Integrator for Leads', desc: 'Lead capture + invoicing', free: false, users: '💼🏢🤖' },
        { name: 'AI Business Name / Branding Generator', desc: 'Names + slogans', free: true, users: '🆕💼🏢🤖' },
    ],
    Automation: [
        { name: 'Bulk Page Generator (Programmatic SEO)', desc: '1000s pages from CSV', free: true, users: '🏠🤖' },
        { name: '1-Click Full Local SEO Automation', desc: 'Niche to Site to GBP to Citations to Reports', free: false, users: '🤖' },
        { name: 'Social Signal Local Connector', desc: 'Post scheduler + NAP inject', free: false, users: '🏢🤖' },
        { name: 'Multi-Language Local SEO Engine', desc: 'Arabic/French/English/Urdu', free: false, users: '🏢🤖' },
        { name: 'Voice Search Data Optimizer', desc: 'Siri/Alexa/Google voice ready', free: false, users: '🏢🤖' },
        { name: 'Bulk Niche to Site to Deploy Pipeline', desc: 'Full bulk automation', free: false, users: '🤖' },
    ],
}

export const userTypes = [
    { emoji: '🆕', name: 'Local SEO Newbie', color: '#3B82F6', tools: 52, desc: 'New to local SEO? Start here with guided step-by-step workflow.', steps: ['Find low-competition niches', 'Build your first local site', 'Setup Google Business Profile', 'Track your rankings'] },
    { emoji: '💼', name: 'Client SEO Pro', color: '#8B5CF6', tools: 107, desc: 'Manage multiple clients with professional SEO tools and white-label reports.', steps: ['Full client management', 'Competitor analysis suite', 'GBP optimization tools', 'White-label PDF reports'] },
    { emoji: '🏠', name: 'Rank & Rent', color: '#F59E0B', tools: 85, desc: 'Build, rank and rent local sites at scale with bulk automation tools.', steps: ['Bulk page generation (5000+)', 'Auto internal linking engine', 'Static site deployment', 'Portfolio management'] },
    { emoji: '🏢', name: 'Agency', color: '#10B981', tools: 132, desc: 'Run a full-service local SEO agency with enterprise tools and team features.', steps: ['Multi-client dashboard', 'Bulk site generation', 'Team collaboration', 'Custom branded reports'] },
    { emoji: '🤖', name: 'Automation/Scale', color: '#EF4444', tools: 141, desc: 'Automate everything — from niche research to deployment at massive scale.', steps: ['1-Click full SEO automation', 'Bulk niche to site to deploy', 'Auto GBP management', 'Scheduled reporting'] },
]

export const compareRows = [
    { feature: 'AI Website Generator', bl: '❌', ld: '❌', lsp: '✅ Basic', us: '✅ Advanced' },
    { feature: 'Programmatic Pages (5k+)', bl: '❌', ld: '❌', lsp: '❌', us: '✅' },
    { feature: 'Internal Linking Engine', bl: '❌', ld: '❌', lsp: '❌', us: '✅' },
    { feature: 'GBP Full Automation', bl: '✅ Partial', ld: '✅ Partial', lsp: '❌', us: '✅ Full' },
    { feature: 'Rank & Rent Automation', bl: '❌', ld: '❌', lsp: '✅ Basic', us: '✅ Complete' },
    { feature: 'Niche Finder Tool', bl: '❌', ld: '❌', lsp: '❌', us: '✅' },
    { feature: 'Static + WP Hybrid', bl: '❌', ld: '❌', lsp: '❌', us: '✅' },
    { feature: '1-Click Full SEO', bl: '❌', ld: '❌', lsp: '❌', us: '✅' },
    { feature: 'Citation Tools', bl: '✅', ld: '❌', lsp: '❌', us: '✅' },
    { feature: 'Geo-Grid Ranking', bl: '✅', ld: '✅', lsp: '❌', us: '✅' },
    { feature: 'Multi-Language', bl: '❌', ld: '❌', lsp: '❌', us: '✅' },
    { feature: 'Monthly Price', bl: '$29-79', ld: '$49-99', lsp: '$97+', us: 'You Decide' },
]

export const pricingPlans = [
    { name: 'Starter', color: '#64748B', price: '$0', period: '/mo', features: ['1 website', '50 pages', 'Phase 1 tools (55 tools)', 'Gemini AI (free)'], excluded: ['GBP tools', 'Rank tracking'], cta: 'Start Free', popular: false },
    { name: 'Pro', color: '#A855F7', price: '$29-49', period: '/mo', features: ['5-10 websites', '500 pages', 'All Phase 1 tools', 'Basic automation', 'Gemini API included'], excluded: ['White-label'], cta: 'Start Pro Trial', popular: true },
    { name: 'Agency', color: '#10B981', price: '$79-149', period: '/mo', features: ['50 websites', '5,000+ pages', 'Full automation', 'GBP + Reports', 'Multi-location', 'Client portals'], excluded: [], cta: 'Start Agency Trial', popular: false },
    { name: 'Enterprise', color: '#F59E0B', price: '$199-299', period: '/mo', features: ['Unlimited websites', 'Unlimited pages', 'All 136 tools', 'White-label', 'Priority support', 'Custom branding'], excluded: [], cta: 'Contact Sales', popular: false },
]
